Name: NotificationManager
Version: 0.1.0
Link: http://www.webiny.com/store/webiny/notification-manager/
Description:

AuthorName: Webiny LTD
AuthorLink: http://www.webiny.com
AuthorEmail: info@webiny.com

Services:
    NotificationManager:
        Class: Apps\NotificationManager\Php\Lib\NotificationManager
    EmailContentHandler:
        Class: Apps\NotificationManager\Php\Lib\EmailNotificationHandler
        Tags: ['notification-manager-handler']
        Scope: prototype
    SlackContentHandler:
        Class: Apps\NotificationManager\Php\Lib\SlackNotificationHandler
        Tags: ['notification-manager-handler']
        Scope: prototype

Storage:
    Services:
        NotificationManager:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        Config:
                            Directory: __DIR__/../../Temp/NotificationManager
                            PublicUrl: __Application.WebPath__/uploads
                            Create: true