Name: NotificationManager
Version: 0.1.0
Link: http://www.webiny.com/store/webiny/notification-manager/
Description:

AuthorName: Webiny LTD
AuthorLink: http://www.webiny.com
AuthorEmail: info@webiny.com