Name: NotificationManager
Version: dev-master
Link: https://github.com/Webiny/NotificationManager
Description: Manage your notifications, emails, slack messages and custom plugins with ease.
Author:
    Name: Webiny LTD
    Email: info@webiny.com
    Link: https://www.webiny.com

Services:
    NotificationManager:
        Class: Apps\NotificationManager\Php\Lib\NotificationManager
    EmailContentHandler:
        Class: Apps\NotificationManager\Php\Lib\EmailNotificationHandler
        Tags: ['notification-manager-handler']
        Scope: prototype
    SlackContentHandler:
        Class: Apps\NotificationManager\Php\Lib\SlackNotificationHandler
        Tags: ['notification-manager-handler']
        Scope: prototype

Storage: Temp