Name: NotificationManager
Version: 0.1.0
Link: http://www.webiny.com/store/webiny/notification-manager/
Description:

AuthorName: Webiny LTD
AuthorLink: http://www.webiny.com
AuthorEmail: info@webiny.com

Services:
    NotificationManager:
        Class: Apps\NotificationManager\Php\Lib\NotificationManager
    EmailContentHandler:
        Class: Apps\NotificationManager\Php\Lib\EmailNotificationHandler
        Tags: ['notification-manager-handler']
    SlackContentHandler:
        Class: Apps\NotificationManager\Php\Lib\SlackNotificationHandler
        Tags: ['notification-manager-handler']

Storage:
    Services:
        NotificationManager:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../../Temp/NotificationManager
                        - __Application.WebPath__/uploads
                        - false
                        - true